- dht.go
- dht_test.go
- notif.go
- package.json
A client mode dht node will not serve any requests, but will still be able to make requests of the network.
I'm interested in pushing this forward as an experimental feature to reduce idle bandwidth consumption.
> Add support for a 'client mode' dht

- handlers.go
to reduce confusion as it is a bug with unknown source but end users
don't have to see it as it isn't critical
Closes https://github.com/ipfs/go-ipfs/issues/2495
> dht: degrade 'no addresses' from error to warning

- dht_test.go
- lookup.go
we were previously filtering out peers that werent as close to us from `GetClosestPeers` calls. This would result in small numbers ( < K ) peers being returned when we expected a full K peers no matter what.
The side effects of that behaviour are things like records not being put to enough peers, and not enough peers being queried during lookups.
> fix filtering bug in find closest peers

- dht.go
It looks like `NewDHT` and `NewDHTClient` are doing almost the same thing. They both have the same comment; maybe explaining the difference in the comments would be useful.
> DRY up NewDHT

- providers/providers.go
- providers/providers_test.go
Before this will even compile https://github.com/ipfs/go-datastore/pull/54 needs to go in and deps updated.
To get the performance improvements  https://github.com/ipfs/go-ds-leveldb/pull/1 needs to go in and deps updated.
> Improve  GetProviders Performance by around 2x

- .travis.yml
- dht.go
- dht_test.go
- lookup.go
- package.json
- pb/message.go
- query.go
- routing.go
So far i've reproduced the issue in a test. The problem is that the 'limited size peerset' is incorrect. It gets filled up with peers from our routing table. Which also brings up the fact that we shouldnt be returning peers from our routing table immediately, they arent super likely to always be the closest peers to our query.
> WIP: fixing getclosestpeers full-peerset bug

- .gx/lastpubver
- package.json
Depends on:
- https://github.com/libp2p/go-libp2p-kbucket/pull/8
- https://github.com/libp2p/go-libp2p-routing/pull/10
This PR with gx updates has been created using gx-workspace: https://github.com/ipfs/gx-workspace
> gx: update go-libp2p-peerstore, go-libp2p, go-libp2p-kbucket

- .gx/lastpubver
- package.json
(and update go-libp2p-routing)
> Update go-cid and gx-publish 2.5.2

- .travis.yml
- routing.go
* Before:
```
22:04:50.513: * <peer.ID > says use <....
```
* After:
```
22:05:38.170: * <peer.ID cqVgfL> says use <.....
```
> Add queried peer ID to query event

- lookup.go
Currently keys that get logged are casted from []byte. Which means that log output looks like this.
```
{"event":"getClosestPeersBegin","key":"\u0012 \ufffdᱡ\ufffd`\ufffdF]\ufffd\ufffdᠸCƶ\u0006E\ufffdrb\ufffd\ufffdO\ufffd\ufffdu\ufffd\ufffdj\u000b","system":"dht","time":"2017-07-27T11:12:08.51775836Z"}
```
after fix like this:
```
{"event":"getClosestPeersBegin","key":"QmQyyaB8znrakGydP3ynRsXre96Uw9wc6w6zuP61bbZuNj","system":"dht","time":"2017-07-27T11:16:30.693008112Z"}
```
> Fix logging of keys.

- dht_net.go
- dht_test.go
- notif.go
This was definitely causing a decent memory leak. I'm sorry.
> fix memory leak holding onto streams unnecessarily

- notif.go
> silence context canceled error

- dht.go
- notif.go
Before, we could end up (e.g.):
1. Creating two connections (both sides connect at the same time).
2. Try to test with the first one.
3. The first connection dies.
4. Get a stream reset and think that the other side doesn't support the DHT protocol.
We tried to fix this by checking for an EOF. Unfortunately, reset streams don't return EOFs.
This commit also simplifies peer tracking (and saves a bit of memory).
fixes #99
> fix connection tracking race

- handlers.go
- handlers_test.go
Explicitly clean DHT records before storing them.
> ensure we don't store arbitrary data

- dht_test.go
- package.json
Update go-libp2p-kad-dht to use new validation function format in https://github.com/libp2p/go-libp2p-record/pull/9
> Just pass the record object to validation functions

- providers/providers.go
License: MIT
Signed-off-by: Jason Chang <ridewindx@163.com>
> Set KeysOnly field of query condition to true for Datastore.Query(), then it will query only keys.

- .gx/lastpubver
- package.json
- records.go
- records_test.go
1. Rely on the peerstore to extract the public key instead of doing so internally (centralize).
2. Update the tests for the changes in go-libp2p-peer.
3. Update a bunch of deps (including go-libp2p-crypto, go-log, etc.)
4. Remove unnecessary progress bar dependency.
> update peer-id public key extraction (and more!)

- dht.go
This small patch improves the docstrings for `NewDHT` and `NewDHTClient`, illuminating the difference between the two otherwise identical calls.
> Add explanation to NewDHT/NewDHTClient doc strings

- dht.go
- dht_net.go
- dht_test.go
- ext_test.go
- notif.go
- opts/options.go
This changeset makes it possible for the DHT to use non-IPFS protocols.
Comments in #152 motivated creating a branch off of `feat/routing-refactor` instead of `master`.
> Make DHT Protocols Configurable

- lookup.go
- query.go
This is a bit of a WIP, but these two changes should be pretty good on their own.
The first is relatively minor, and just uses a more optimal method for checking if we have a connection to a peer.
The second one changes `GetClosestPeers` to only return the peers from its query that it was actually able to connect to. This is *strictly* better than the current code, as currently we return a set of peers that we are either already connected to (and the query knows this) or we have already failed to dial them (and the query knows this). Where the end result is we basically fail to put records to the peers that the query has already failed to connect to. So theres really no point in returning these peers to the caller, as we *just* tried and failed to connect to them.
> dht query improvements

- dht.go
- dht_test.go
- handlers.go
- routing.go
Also deduplicates some validation code.
> validate on local put

- dht_net.go
The Protobuf writer performs multiple small writes when writing a message. We need to buffer these, otherwise we'll send out a packet for each Write call.
This will reduce the number of packets sent when providing records by 75%.
Verified that it works by looking at the QUIC packet log. Every DHT record is now sent in a single packet.
> buffer writes when sending protobufs

- dht_test.go
- ext_test.go
- routing.go
- routing_options.go
This exposes new function which streams entries as they are found - https://github.com/libp2p/go-libp2p-routing/blob/master/routing.go#L61
Part of https://github.com/ipfs/go-ipfs/issues/5232
Replaces https://github.com/libp2p/go-libp2p-kad-dht/pull/49
TODO:
* More tests
* Error handling feels weird
> Implement SearchValue

- .gx/lastpubver
- dht.go
- dht_test.go
- package.json
- providers/providers.go
- providers/providers_test.go
- routing.go
See https://github.com/ipfs/go-cid/pull/71 for additional info.
Depends on:
Which Depends on:
- https://github.com/ipfs/go-cid/pull/71
Please approve but do not merge. Depends on locally pinned hashes.
> gx update and fix code to use new Cid type

- handlers.go
handlers.go line 301:
```go
lm := make(lgbl.DeferredMap)
lm["peer"] = func() interface{} { return p.Pretty() }
eip := log.EventBegin(ctx, "handleGetProviders", lm)
defer eip.Done()
// ...
lm["key"] = func() interface{} { return c.String() }
```
The last line does not work and the `key` does not appear in the log message. And I see that the `EventBegin` has been deprecated, so I changed all `EventBegin` to `Start`.
> Some key-value is missing in the log

- records_test.go
This has temporarily been disabled due to the changes/issues described in:
https://github.com/libp2p/specs/issues/111
> tests: skip key inlining test

- dht_bootstrap.go
Also contained in "dht.go" and prints twice in godoc.
https://godoc.org/github.com/libp2p/go-libp2p-kad-dht
> docs: duplicate pkg documentation

- query.go
Without this, one of the workers may hang when trying to re-grab the rate-limit after dialing. I believe this may be what's causing some of our DHT requests to stall (evidence: massive goroutine buildup on the gateways).
> fix a potential DHT query hang

- dht.go
- dht_bootstrap.go
- doc.go
- query.go
Both dht.go and `dht_bootstrap.go` duplicate the package documentation.
The whole block had been moved to doc.go
Also `query.go` provides documentation for query package but now it
belongs to `dht` package, so it's been removed.
The following image highlights the duplicated and outdated documentation blocks:
> Remove outdated package documentation

- dht_bootstrap.go
- dht_test.go
Remove IpfsDHT.BootstrapOnSignal. This is behaviour that can be achieved without intruding on IpfsDHT. It's not used elsewhere. The tests are retained and adapted to work without the method.
> Remove signal bootstrapping

- dht_bootstrap.go
- dht_test.go
Reverts libp2p/go-libp2p-kad-dht#224
> Revert "Remove signal bootstrapping"

- dht.go
- dht_bootstrap.go
- dht_test.go
- routing.go
Refactor bootstrapping to remove goprocess, and use contexts properly. Also includes some interface assertions for future refactoring.
> Tidy up bootstrapping

- dht.go
- dht_bootstrap.go
- dht_test.go
- routing.go
Reverts libp2p/go-libp2p-kad-dht#225
This was never approved and was still under discussion.
> Revert "Tidy up bootstrapping"

- dht_bootstrap.go
This is useful for two specific cases in the libp2p code base at present. go-libp2p-examples/chat-with-rendezvous, and the go-libp2p-daemon.
> Add the full libp2p default bootstrap peer list

- dial_queue.go
- dial_queue_test.go
- query.go
Currently the DHT is performing dials outside of the Alpha concurrency limit. We are dialling all nodes that peers return in `CloserPeers` without limit. As a result, we end up flooding the swarm with dial jobs, which trips over the file descriptor limits, and brings dialling to a halt under some circumstances. Our current approach is also algorithmically incorrect, and leads to suboptimal query patterns.
This patch introduces an adaptive dial queue that spawns a dynamically sized set of goroutines to preemptively stage dials for later handoff to the DHT protocol for RPC. It identifies backpressure on both ends (dial consumers and dial producers), and takes compensating action by adjusting the worker pool.
We start with `DialQueueMinParallelism` number of workers (6), and scale up and …
> Adaptive queue for staging dials

- dial_queue.go
- dial_queue_test.go
- query.go
> Fix races with DialQueue variables

- dial_queue.go
- dial_queue_test.go
- query.go
Also wrapped the args to the `newDialQueue()` constructor in a struct, to avoid an obscene arity. Gives us more flexibility in the future. Inspired by the style of [aws-sdk-go](https://godoc.org/github.com/aws/aws-sdk-go).
For now these types and functions remain private.
_Follow-up to https://github.com/libp2p/go-libp2p-kad-dht/issues/239#issuecomment-459250772._
> Make dial queue parameters configurable

- dht.go
- dht_bootstrap.go
- dht_net.go
- dht_test.go
- dial_queue.go
- ext_test.go
- handlers.go
- lookup.go
- query.go
- records.go
- routing.go
Rename the IPFS dht logger instance from `log` to anything other than `log`. It makes it very difficult to do quick instrumentations of the code for debugging using the standard library `log` package.
> Rename log to logger

- .travis.yml
- Makefile
Include the go mod tests on Travis, they're still relevant even without the major versioning.
> Include Travis go mod tests

- dht_net.go
In particular, unnecessary goroutine use, some alterations to reset handling, log levels, and when to update the peer for successful interaction.
> Rework handleNewStream

- dial_queue.go
On context cancellation, the `ChanQueue` stops its loop but keeps the `EnqChan` channel open. Under the right conditions, this could cause a worker goroutine to leak by blocking forever when sending to `EnqChan`, as nobody would be receiving any longer.
This race is fixed by attaching a separate context to the `ChanQueue` whose cancellation we control. Only after all workers have yielded (fenced by a `WaitGroup`), do we close the `ChanQueue`.
---
EDIT: force pushed a simpler solution as suggested by @Stebalien: https://github.com/libp2p/go-libp2p-kad-dht/pull/262#pullrequestreview-205009617
> dial queue: fix possible goroutine leak

- dht_bootstrap.go
- query.go
This fixes bootstrap "sub-queries" when the sub-query timeout is triggered with `DeadlineExceeded`. Currently the sub-query timeout is not handled correctly, and query timeouts are not propagated correctly.
> Fix Bootstrap sub-queries

- dht_net.go
- dht_test.go
We usually _explicitly_ call connect before calling `prep` but we may disconnect somewhere in-between. We _don't_ want to get stuck here dialing if the context has been canceled.
> thread context to prep

- dht_bootstrap.go
It's more helpful to know what's going on between the bootstrap sub-queries, I've found myself using this change for testing several PRs. In particular, this helps with testing improvements to the bootstrap default config, and determining the value of random vs. targeted bootstrap subqueries.
> Log before and after bootstrap sub-queries

- query.go
When a peer is found, add its addrs to the peerstore, just like the addresses for closer peers are added. In particular this is helpful for followup queries by the DHT user.
I'm not sure about the TTL, and the fact that addresses are deferred to the peerstore at all for the DHT, but it's an improvement nonetheless and came up messing around with the [DHT tool](https://github.com/anacrolix/go-libp2p-dht-tool).
> Add find peer success addrs to peerstore

- dht_bootstrap.go
It's impossible to find the self ID in the DHT because of this statement https://github.com/libp2p/go-libp2p-kad-dht/blob/ac6772539b80d687c8ed711024b104aaa881c1d6/handlers.go#L257
So maybe we should ignore the "not found" error in this case, like we do it for the random walk.
> Get rid of annoying "bootstrap: not found" warning

- dial_queue.go
Don't start the control loop till we start the queue. The _in_ queue will still work, we just won't start processing peers from it until we start the control loop.
fixes #311
> dialQueue: start the control loop later

- opts/options.go
I've opted to remove the old protocol from the defaults, separately from any stream changes, so as not to conflate any changes in behaviour.
> Remove the old protocol from the defaults

- providers/providers.go
- providers/providers_test.go
Otherwise, we'll delete everything.
> fix(providers): gc

- providers/providers.go
Motivation: Walking the datastore can take time and currently blocks adding/removing providers.
We need to do this in the same goroutine to avoid some logical races.
Alternative to #324
> providers: run datastore GC concurrently

- query.go
Long-running queries can build up large error sets that we never actually use.
This is exacerbated by https://github.com/libp2p/go-libp2p-swarm/pull/115.
fixes https://github.com/libp2p/go-libp2p-swarm/issues/119
> query: fix error "leak"

- metrics/metrics.go
Exposes all the views in a slice for convenience, and because they're self-describing.
> Expose metrics views in a slice

- query.go
- routing.go
When the routing table is empty, `Run` would fail but _not_ close the process (leaking some query goroutines). This patch fixes this in multiple places by:
1. Not starting queries with no peers.
2. Failing queries with no peers earlier.
> query: fix a goroutine leak when the routing table is empty

- dht_net.go
Allocate them as-needed and use a pool.
Work towards #322.
> fix: reduce memory used by buffered writers

- dht_net.go
- go.mod
- go.sum
* Kill idle inbound streams after 10 minutes. We should also do outbound streams
but we can handle that separately.
* Reduce the number of goroutines used by inbound streams by 1 by not bothering
with the "context reader".
> reduce background goroutines

- lookup.go
- routing.go
We noticed some odd behavior around the provide call https://github.com/ipfs/go-ipfs-provider/pull/8
> Add timeout

- metrics/metrics.go
- routing.go
Right now this is a very simple metric: the time that has elapsed between calling `routing.Provide` and sending the first `putProvider` message.
> Add Time To First Provider record metric

- dht_net.go
- go.mod
fixes #389
Credit goes to @sidenaio for finding this.
> metrics: fix memory leak

- go.mod
- go.sum
Fixing for go 1.13 (see golang/go#34093).
Closes #385. Verified on my local machine. (I've seen #391 after I've made that, a bit duplicate but mine have less impact (it only change `golang.org/x/xerrors`), that your choice)
> Fixing for go 1.13

- dht.go
- dht_bootstrap.go
- dht_test.go
- ext_test.go
- notif.go
- opts/options.go
@Stebalien 
This takes #402 to completion. Main changes made are:
1. Bootstrap(ctx) should be synchronous so that errors in bootstrapping flow to the client
2. A flag to disable auto bootstrapping so that tests which depend on a specific number of peers in the RT/query results do not fail
3. Replace RoutingTableScanInterval with BucketPeriod.
> feat(bootstrap): take autobootstrap to completion

- dht.go
- dht_bootstrap.go
- dht_test.go
- ext_test.go
- go.mod
- go.sum
- notif.go
- opts/options.go
* Don't bootstrap more than 16 buckets: We can't generate target IDs in buckets beyond bucket 15 so there's no point.
* Bootstrap sequentially: The default timeout is 10s so this won't take that long anyways. On the other hand, if we do this all at once, we max the swarms dial queue.
* Rename triggerAutoBootstrap to autoBootstrap. This variable used to control _triggering_ only but now completely disables automatic bootstrapping.
* Remove the BootstrapConfig. We introduced this before we switched to functional options. Now that we're breaking the interfaces anyways, we might as well use functional options all the way (easier to extend).
* Always query self when bootstrapping. This really isn't that expensive and ensures that we know how many buckets we _should_ bootstrap.
* Don't abort …
> fix and simplify some bootstrapping logic

- dht.go
- handlers.go
- opts/options.go
- records.go
> Make max record age configurable

- dht.go
- dht_bootstrap.go
- dht_test.go
- go.mod
- go.sum
- notif.go
We'd like to be able to refresh then _wait_ for the refresh to finish in the testground DHT tests. That way, we can:
1. Start and disable _auto_ refresh.
2. Bootstrap.
3. Refresh a couple of times till we're stable.
4. Wait to _stop_ refreshing.
5. Disconnect from and forget about all peers _not_ in our routing tables.
6. Run the actual tests without interference from the bootstrapping logic.
> feat: refresh and wait

- dht_test.go
- notif.go
Otherwise, we could decide to _not_ add a peer, disconnect from most peers, and
be unable to query the DHT even if we're technically connected to a peer in the
DHT.
This is a small subset of active bootstrapping.
> fix: try to re-add existing peers when the routing table is empty

- go.mod
- go.sum
Fixes a bug where we wouldn't be able to perform queries with a sparse but
non-empty routing table.
> chore(dep): update kbucket

- dht.go
Thanks @Stebalien and @daviddias for the explanations!
License: MIT
Signed-off-by: Henrique Dias <hacdias@gmail.com>
> fix: prioritize closer peers

- dht.go
- dht_test.go
- handlers.go
- opts/options.go
- records_test.go
- routing.go
> feat: allow disabling value and provider storage/messages

- dht_bootstrap.go
- dht_test.go
Otherwise, we'll just return a channel that will never be signaled.
> fix: always send the result channel when triggering a refresh

- dht_bootstrap.go
- go.mod
- go.sum
- lookup.go
- routing.go
@Stebalien 
For #406
Finishes the change proposed in 406. Please take a look when you the time.
> Refresh cpl's in dht

- dht_bootstrap.go
- go.sum
1. Remove bootstrappers with small (1024 bit) keys.
2. Switch from /ipfs to /p2p multiaddrs.
part of https://github.com/libp2p/libp2p/issues/79
> chore(bootstrap): update bootstrappers

- dht_test.go
For #426 
@Stebalien Please review.
**Proof**
```
GO111MODULE=on go test -count 500 -run TestEmptyTable
PASS
ok  	github.com/libp2p/go-libp2p-kad-dht	36.979s
```
There is nothing that will prevent all the peers from being added to the RT if the stars/randomly generated hostID cpl's align. We should remove one peer from the RT so that not all peers end up getting disconnected.
> Fix flaky TestEmptyTableTest

- dht.go
- dht_test.go
- go.mod
- go.sum
- handlers.go
- lookup.go
- lookup_test.go
- providers/providers.go
- providers/providers_test.go
- routing.go
This makes it so that provider records use multihashes instead of CIDs, solving the most important part of  https://github.com/libp2p/go-libp2p/issues/755. This is effectively a wire protocol fix and does not change any of the external facing DHT APIs.
Note: This change will have a network breaking effect for users advertising provider records for CIDv1 CIDs, but should not effect anyone using CIDv0 CIDs.
> Provider records use multihashes instead of CIDs

- dht_net.go
It's currently 10 minutes. This change will kill all inbound DHT streams that haven't been used in 1 minute.
We keep streams around to avoid the cost of setting up new streams (the multistream overhead, mostly). However, each one of these takes at least one goroutine and some other state.
Ideally, this will let us run multiple DHTs side-by-side without keeping one stream per peer per DHT open.
> feat: reduce stream idle timeout to 1m

- dial_queue.go
see https://github.com/libp2p/go-libp2p-kad-dht/issues/453#issuecomment-591920081
> fix(dialqueue): fix a timer leak

- dht_net.go
Stumbled upon this while working on https://github.com/libp2p/go-libp2p-kad-dht/issues/453
The metric for message/request sent/received was not incremented when an error occurred but the error count was. This would lead to a meaningless error ratio.
> metrics: record message/request event even in case of error

- ctx_mutex.go
- dht_net.go
- ext_test.go
- notif.go
Related to #453 but not a fix. This will cause us to actually return early when we start blocking on sending to some peers, but it won't really _unblock_ those peers. For that, we need to write with a context.
> fix: obey the context when sending messages to peers

- ext_test.go
- lookup.go
- routing.go
We used to run GetClosestPeers till the context was _about_ to expire, then we'd do the put. That way, we'd succeed even though our query logic was broken. We no longer need to do that.
> Fix context handling and the TestHang test

- dht.go
- dht_options.go
- dht_test.go
- ext_test.go
- opts/options.go
- protocol.go
- records_test.go
Rational:
1. This allows us to make private options for testing.
2. This removes an import for DHT users.
3. This makes options much easier to discover.
4. This makes it possible to make the config/options internals private.
We originally put them in a sub-package to avoid poluting the root namespace,
but that isn't really necessary.
This keeps the old package (for now) to avoid breaking too much.
> feat: move options to main package and make internals private

- dht.go
- dht_net.go
- dht_options.go
- dht_test.go
- ext_test.go
- opts/options.go
- records_test.go
- subscriber_notifee.go
Relates to libp2p/go-libp2p#780
- Allows for DHT upgrades by having different client and server protocols
- Updates the default protocol IDs.
- Includes a defensive check against people messing with DHT options but still utilizing the default protocol ID
Is currently targeted as merging into `feat/mode-switching`, but after #469 is merged this PR will be redirected to merge onto `cypress`
> Upgrade DHT version

- dht.go
- dht_test.go
- handlers.go
- providers/providers.go
- providers/providers_test.go
- routing.go
> feat: Expose the ProviderManager through the IpfsDht struct

- providers/provider_set.go
- providers/providers_manager.go
- providers/providers_manager_test.go
- providers/providers_test.go
Hi folks! As I was going through #487, I found myself having to jump often through the code and keep a lot of things in my brain cache to parse through the codebase, nothing terrible but I couldn't resist the urge to order things a bit and add some code comments.
I hope this refactor is non contentious. It mostly does:
> refactor: ProviderManager

- dht.go
- notify_test.go
For https://github.com/libp2p/go-libp2p-kad-dht/issues/494
> Fix test logging & document timing issue on Windows

- dht.go
- dht_options.go
- go.mod
- go.sum
@Stebalien @aschmahmann 
RT PR at https://github.com/libp2p/go-libp2p-kbucket/pull/59
> RT peer validation should also include support for the DHT protocol

- go.mod
- go.sum
For https://github.com/libp2p/go-libp2p-kad-dht/issues/524
> Bump peerstore version in cypress

- dht_net.go
This should stop us from waiting on unresponsive peers. This only kicks in when we've already _sent_ a request so this:
* Shouldn't be blocked on other requests we're planning on making.
* Shouldn't be blocked on dialing.
We already have a 5s tcp timeout so I'm pretty sure this is the timeout that's slowing us down on the live network.
> feat: reduce request read timeout

- dht.go
- handlers.go
Previously, we'd only return the target peer if we were connected to them. However, this makes it difficult to impossible to find peers that are mostly disconnected from the network.
This change also changes `p` to `from` in several places as `p` is _very_ confusing. We should probably switch away from using `p` everywhere.
> feat: return target peer if we know about them

- dht.go
- dht_bootstrap.go
- dht_test.go
- go.mod
- go.sum
- subscriber_notifee.go
@aschmahmann 
For #521  and makes fixLowPeers more active.
RT peer at https://github.com/libp2p/go-libp2p-kbucket/pull/69.
> Periodic Pinging and active fixLowPeers

- dht_bootstrap.go
This should allow us to get a better picture of what's going on during internal processes like routing table refreshes and self lookups.
Not sure if there's anywhere else the plugging is missing here, but this seems like it's it.
> use dht context during refreshes so that they can be logged

- dht.go
- dht_options.go
- dht_test.go
- ext_test.go
- subscriber_notifee.go
When this option is passed, the DHT node will listen on and query _only_ using the old DHT protocol. Importantly, the node won't even pretend to be a new DHT node because it's routing table includes V1 peers.
> feat: add a v1 compatibility mode

- routing.go
🤦‍♂
@Stebalien do we want a unit test here that just checks that we don't panic when doing a FindProviders with an empty routing table, or not worth it?
> fix incorrect error handling during provider record lookups

- dht_test.go
- handlers.go
- handlers_test.go
- lookup.go
- pb/message.go
- routing.go
Handle empty keys, both when sent in RPC requests and in the local API.
> fix: handle empty keys

- dht_filters.go
- dht_filters_test.go
- dht_test.go
- go.mod
- subscriber_notifee.go
Also, cache routing info so we don't need to repeatedly recompute it.
We should also consider caching known-filtered peers... but we can do that after
profiling.
> fix: use the routing table filter

- handlers.go
It doesn't actually work. Blocks are stored under /blocks and have been since 2015.
Furthermore, this is just wrong. We shouldn't go digging through the datastore to see if we happen to have the block. If we want something like this, we should include a blockstore in the provider manager.
> fix: remove local provider check

- dht.go
- dht_bootstrap.go
- dht_net.go
- dht_options.go
- dht_test.go
- events.go
- lookup.go
- protocol.go
- query.go
- records.go
- routing.go
Here's some fixes for linter warnings so my editor doesn't appear so yellow.
⚠️ there's a change to an error message - I don't know if this is considered breaking in golang.
There's also a bunch of linter warnings in `dht_test.go` for passing `ctx` as the first parameter, but I also read somewhere that `t` should be passed first (as it is) so I don't know who's most correct.
P.S. may I have write perms?
> chore: linting fixes

- dht.go
- dht_options.go
- dht_test.go
- dual/dual.go
- dual/dual_test.go
- go.mod
- go.sum
- internal/testing/helper.go
- subscriber_notifee.go
> Dual DHT scaffold

- dht.go
- dht_bootstrap.go
- go.mod
- go.sum
- query.go
Need to set the maxThreshold correctly.
> Fix bug in periodic peer pinging

- dual/dual.go
1. FindPeer should succeed as long as we find the peer in one DHT.
2. If we get a kbucket error from one DHT, return the error from the other DHT.
3. Avoid returning the same error twice.
> fix: improve error handling in dual dht

- dual/dual.go
That way, external users can easily determine which DHT they should use. E.g., in go-ipfs, I'd like to call GetClosestPeers in the `ipfs dht` commands based on the "active" DHT.
> feat: expose WANActive

- dht_filters.go
This function is called frequently, let's avoid allocating as much as possible.
> fix: optimize isRelay

- query.go
As far as I can tell the list of peers is not being shuffled in this function. In addition [`NearestPeers`](https://github.com/libp2p/go-libp2p-kbucket/blob/a8232c8ad2e784b3966d04f86a28f9223d1d11a8/table.go#L323) returns them in sorted order.
Hope I am not missing something.
> query.go: Remove shuffle comment

- dht_filters.go
> stricter definition of public for DHT

- dht.go
- dht_net.go
- go.mod
- go.sum
These are all critical paths so we should try to do as little work as possible.
> chore: optimize debug logging a bit

- dht.go
- dht_options.go
- providers/providers_manager.go
- providers/providers_manager_test.go
This PR enables the provider manager to accept options and exposes the `cleanupInterval` and `cache` (cache implementation) as options that can be set.
This also adds `providersOptions []providers.Option` as a main option to the DHT.
Currently _all_ Hydra _heads_ share a datastore and they _all_ perform GC on that same datastore. We really only need one Hydra head to perform GC. Exposing the `cleanupInterval` option allows us to disable GC on all other heads (by setting it really high).
Originally I opened https://github.com/libp2p/go-libp2p-kad-dht/pull/591 to expose the `ProviderManager` as a constructor option, the idea being to construct a single provider manager instance and pass it to all DHTs. However, this would have only solved the GC problem for a single Hydra i.e. we wouldn't …
> feat: set provider manager options

- dual/dual.go
If either of the DHTs fails to find providers, an error event is emitted that clients may misinterpret. This change will hold off on sending such an error unless it's the only event to come out of both the WAN and LAN DHTs.
fix #602
> intercept failing query events when finding providers

- dht.go
- query.go
- routing.go
- subscriber_notifee.go
1. When a peer changes their listening addresses, we need to re-run our routing table filters, possibly removing them.
2. When a peer _starts_ supporting the DHT protocol, we need to add them to our routing table. Previously, we'd only do the inverse.
3. Don't add temporary, discovered addresses to our peerstore if we have better ones. That's a very bad idea.
Depends on https://github.com/libp2p/go-libp2p/pull/898
> fix: re-validate peers whenever their state changes

- dual/dual.go
This will eventually exit when the query completes, but we could spin for a
while in the mean-time and prevent other goroutines from being scheduled.
> fix: don't spin when the event channel is closed

- dht.go
- dht_bootstrap.go
- dht_bootstrap_test.go
- dht_options.go
- dht_test.go
> Double the usefulness interval for peers in the Routing Table

- dht.go
- query.go
That way, we never disconnect from the core of the network.
We don't protect our closest peers as:
* We'll reconnect to them frequently when we query for ourself.
* We use the core nodes most frequently.
> fix: protect useful peers in low buckets

- query.go
This fixes the rare race from https://github.com/ipfs/go-ipfs/issues/7312.
The bug was that with particular timings if a lookup's context was cancelled then the lookup followup queries could continue even after the routing layer function (e.g. FindProvidersAsync) had returned to the called. This enabled the lookup followup for functions like FindProvidersAsync to try and write to a channel that had been closed, causing the panic.
This PR doesn't return control to the caller until after all the followup goroutines are cleaned up.
Note: I tried writing a test for this, but triggering this bug has proven pretty difficult since we were cancelling the followup query context when we returned to the user which means the window for this bug appearing seems quite small. Any suggestions are …
> fix: lookup context cancellation race condition

- dht.go
- dht_options.go
- dht_test.go
- dual/dual.go
- go.mod
- go.sum
- rt_diversity_filter.go
- rt_diversity_filter_test.go
- rtrefresh/rt_refresh_manager_test.go
Kbucket PR at https://github.com/libp2p/go-libp2p-kbucket/pull/88.
> Peer Diversity in the Routing Table

- dht.go
- query.go
Anything else is easy to game. This way, we remain connected to the core peers and slightly prefer all others.
Pruning doesn't really matter as we'll just reconnect. The only concern is that this will lock in 40 connections. However, that's nothing for libp2p anyways. and the DHT will create that many connections _just_ for a single query.
> feat: protect all peers in low buckets, tag everyone else with 5

- dual/dual.go
- dual/dual_test.go
This is a BREAKING CHANGE for the dual DHT but it should be a relatively minor one.
> feat: allow passing custom dual-dht options

- dual/dual.go
Needed by tests to disable things like diversity filters for WANs.
> allow overwriting builtin dual DHT options

- dht.go
- dht_bootstrap.go
The git diff makes this look more invasive than it really is.
All I did was pull some logic out of fixLowPeersRoutine into a separate function and make it public. None of the functionality has been changed.
> Run fixLowPeers on startup

- dht.go
- dht_options.go
- dht_test.go
- subscriber_notifee.go
fixes #697
We seem to have a ordering problem where https://github.com/libp2p/go-libp2p-kad-dht/blob/7db4172fea89359edcbb7624c25529bd7c27304f/dht.go#L212-L227
`subscriberNotifiee` is called before `rtPeerLoop` is started this means that:
https://github.com/libp2p/go-libp2p-kad-dht/blob/7db4172fea89359edcbb7624c25529bd7c27304f/subscriber_notifee.go#L59-L64
is called which calls:
https://github.com/libp2p/go-libp2p-kad-dht/blob/7db4172fea89359edcbb7624c25529bd7c27304f/dht.go#L682-L686
which happens before we've started processing the channel in `rtPeerLoop`  https://github.com/libp2p/go-libp2p-kad-dht/blob/7db4172fea89359edcbb7624c25529bd7c27304f/dht.go#L626
> Fix constructor ordering

- crawler/crawler.go
- crawler/options.go
> Add basic crawler

- dual/dual_test.go
If we have, e.g., multiple transports, we'll have multiple addresses. Really, we were just trying to make sure the DHT returned unique addresses.
> test: fix unique addr check

- fullrt/dht.go
- fullrt/dht_test.go
Building off of #717, although this PR has been updated to fix issues with #717 in addition to a few more
> fullrt dht bug fixes

- fullrt/dht.go
- fullrt/dht_test.go
Reworked full batching so that it's more explicitly peer oriented rather than key oriented.
There's still room for improvement here on dealing with slow peers (e.g. having more message-based rather than peer-based parallelism).
Some tests on a 2 core machine with about 800k CIDs being provided (after a fresh crawl, although that is hopefully not super relevant)
- Using the current heuristic: 20-30 minutes to provide and about 17/20 peers received each record
- Waiting a full timeout for each message: ~1hr to provide and about 19-20/20 peers received each record
- Aborting after rough 7/20 peers received each record: 5 minutes
> fullrt rework batching

- rtrefresh/rt_refresh_manager.go
> Routing table refresh should NOT block

- query.go
1. Will help in NOT evicting peers from the RT because of the connection manager churn.
2. Once we move to QUIC, the connection times should anyways hopefully be insignificant.
On the other hand, this could slow down queries for lower CPLs for _now_ if the other guy keeps disconnecting from us because we are not in their Routing Table.
> Dont count connection times in usefulness

- dht_test.go
- routing.go
This was a somewhat strange interface that returned one value from each _peer_. It has been replaced by `SearchValue` that returns better and better values as we get them.
In the future, we should be able to introduce a _new_ `GetValues` that returns a "bag" of values (possibly multiple values from individual peers).
fixes #416 
While breaking, there are currently no users of this method. This used to be used in namesys, but that now uses `SearchValue`.
> feat: delete GetValues

- dht.go
- fullrt/dht.go
- internal/errors.go
- pb/protocol_messenger.go
- routing.go
Validation being done inside the ProtocolMessenger was a bit annoying for anyone trying to utilize the protocol messages more directly (debugging, making an alternative client, etc.).
Additionally, this fixes a bug where even though `WithValidation` appeared optional the ProtocolMessenger actually panicked if you didn't pass one in and called `GetValue()`.
> Extract validation from ProtocolMessenger

- handlers.go
Fix
```
adding provider%!(EXTRA string=from, peer.ID=Qmbs3VhnSz7V5DTQt9FXb7iYnWcyHiEMDYisoR1cPno84A, string=key, internal.LoggableProviderRecordBytes=bciqfn7ajoxq3kfhtak5g66chbodhumhpx6kydwhishcnhz3ngft6igy)
```
Logging string
> fix: incorrect format handling

- providers/providers_manager.go
It was previously defined in the `peerstore` package, but we removed it from there (see https://github.com/libp2p/go-libp2p/pull/1835/commits/0e1b7dfd5308c0cdf122dce78fabbe44916163de), because kad was the only consumer.
This PR will be necessary to update go-libp2p to v0.24.0, here and in kubo.
> define the ProviderAddrTTL in this repo

- providers/providers_manager.go
This PR materializes the discussion in [libp2p/specs#451](https://github.com/libp2p/specs/pull/451#issue-1372605284) increasing the provider record's default `TTL` or `ProvideValidity` from `24h` to `48h` based on [RFM17](https://github.com/protocol/network-measurements/blob/master/results/rfm17-provider-record-liveness.md).
The measurements from RFM17 were quite promising for the steady provider record's liveness gathered in the IPFS live network. Based on the average of 70% of online PR holders and 70% of PR holders being among the 20 closest peers for over +48 hours, we suggest increasing the republish interval for the CIDs and extending the expiration time to help reduce part of the overhead that providing large sets of CIDs implies.
**Why 48 hours?**
Since the republish interval is …
> feat: increase expiration time for Provider Records to 48h (RFM17)

- internal/config/config.go
- providers/providers_manager.go
This PR aims to increase the default value for the IPNS records stored through the PUT_VALUE method from `36h` to `48h` based on [RFM17](https://github.com/protocol/network-measurements/blob/master/results/rfm17-provider-record-liveness.md) as discussed in [libp2p/specs#451](https://github.com/libp2p/specs/pull/451#issue-1372605284). 
The measurements from RFM17 were promising and have led to modifying the current republish-interval ([ipfs/kubo#9326](https://github.com/ipfs/kubo/pull/9326)) and record's expiration time ([libp2p/go-libp2p-kad-dht#793](https://github.com/libp2p/go-libp2p-kad-dht/pull/793)). This PR aims to homogenize the expiration of the records to `48h`.
- Increase `Config.MaxRecordAge` from `36h` -> `48h`
> feat: increase the max record age to 48h (PUT_VALUE, RFM17)

- dht.go
- rtrefresh/rt_refresh_manager.go
We have seen in the past that there are peers in the IPFS DHT that let you connect to them but then refuse to speak any protocol. This was mainly due to the resource manager killing the connection if limits were exceeded. We have seen that such peers are already pushed to the edge of the DHT - meaning they get pruned from lower buckets. However, they won't get pruned from higher ones because we only try to connect to them and not speak anything on that connection.
This change adds a ping message to the liveness check on routing table refreshes.
> feat: ping peers on routing table refresh

- fullrt/dht.go
- fullrt/options.go
Introduce new options such that the following can be configured, with fallback onto the existing hardcoded values:
* network crawl interval
* success wait fraction
* bulk send parallelism
* timeout per operation
> Introduce options to parameterize config of the accelerated DHT client

- crawler/crawler.go
- crawler/options.go
- fullrt/dht.go
- fullrt/options.go
The accelerated DHT client uses a fixed implementation of DHT crawler with a parallelism hardcoded to 200. This offers a reasonable general case default behaviour but limits experimentation with alternative crawling strategies with varied or dynamic degree of parallelism.
To avoid this the changes here:
* refactor the existing `Crawler` to `DefaultCrawler`
* introduce `Crawler` as interface type, and
* add option to set the `Crawler` in the accelerated DHT client with fallback to `DefaultCrawler` at parallelism of 200.
As a result the net functionality of the code remains unchanged while it allows the crawling logic to be swapped entirely with an alternative implementation.
Additionally, the changes here parameterize the dial addr extend duration with fallback to the previously hardcoded …
> Allow DHT crawler to be swappable

- routing.go
The current logic of the `PeerSet` (taking the name from the previous `go-libp2p-core/peer.Set`) defines the result of the lookup process based on the first `AddrInfo` that we discover from the lookup for each provider. 
We have spotted in [`RFM17.1`](https://github.com/protocol/network-measurements/pull/22) that this logic would severely impact the effect of extending the provider Multiaddress' TTL [`#795`](https://github.com/libp2p/go-libp2p-kad-dht/pull/795), forcing in some occasions to make that second DHT lookup to map the `PeerID` with the `Maddrs` when it wouldn't be necessary because other PR Holders still have a valid `Maddrs`.
This PR aims to solve that weird behavior from the `PeerSet` by notifying as well whenever a second PR for the same provider comes with the `Maddrs`.
to …
> Adjust PeerSet logic in the DHT lookup process

- providers/providers_manager.go
For context: https://github.com/ipfs/kubo/issues/9264
---
We keep the Multiaddresses of providing peers around for much longer as this means we'll return them alongside the provider records and likely make the second DHT lookup for the peer record obsolete.
The assumption is that peers don't change network addresses often.
For context: https://github.com/ipfs/kubo/issues/9264
> Increase provider Multiaddress TTL

- providers/providers_manager.go
https://github.com/libp2p/go-libp2p-kad-dht/pull/795 was defining `ProviderAddrTTL` a second time, after it was already added in https://github.com/libp2p/go-libp2p-kad-dht/pull/797
cc: @marten-seemann @dennis-tra
> Fix multiple ProviderAddrTTL definitions #795

- lookup_optim_test.go
As @guillaumemichel pointed out, the test were not only failing because of their flakiness but also because some formatting was incorrect and a deprecated API was used.
See this comment: https://github.com/libp2p/go-libp2p-kad-dht/pull/783#issuecomment-1497384112
This PR fixes both issues.
> fix: optimistic provide ci checks in tests

- CODEOWNERS
- README.md
I tried to split code ownership between go-libp2p and kubo maintainers. Please let me know your thoughts
https://github.com/libp2p/go-libp2p-kad-dht/issues/825
> Specified CODEOWNERS

- dht.go
- dht_options.go
- dht_test.go
- dual/dual.go
- internal/config/config.go
Filters are only set for the Dual DHT. Is that correct? Do they also need to be set for other ways to initialize the DHT?
> filter local addresses (for WAN) and localhost addresses (for LAN)

- dht_net.go
The current implementation of the **handleNewMessage** function exclusively processes messages in server mode, generating error logs and returning false for non-server mode cases. This leads to a repetitive logging of this error message whenever the node isn't in server mode:
`ignoring incoming dht message while not in server mode`
This PR enhances the function by elevating the error log to the debug level.
> Enhance handleNewMessage Server Mode Logging: Convert Error Logs to Debug Level

- v2/backend_provider.go
- v2/backend_record.go
- v2/config.go
- v2/coord/coordinator.go
- v2/coord/coordinator_test.go
- v2/coord/telemetry.go
- v2/dht.go
- v2/tele/tele.go
- v2/telemetry.go
Decouple dht and coordinator metrics so we separate responsibilities cleanly. Both components will use the same meter and tracer providers by default.
This also removes the error return from DefaultCoordinatorConfig() which was only needed because it was initializing a Telemetry struct with metrics that it does not touch.
> Give dht and coordinator their own telemetry instances

- v2/backend_provider_test.go
leveldb synchronization seems to behave differenlty on Windows vs. Linux/MacOS which lead to failing tests.
> Use MapDatastore for provider backend tests instead of leveldb

- v2/coord/routing/probe.go
- v2/coord/routing/probe_test.go
@iand could you take over, refine, and fix?
> fix: avoid panic when node is re-added to probe list

- .github/workflows/go-test.yml
- v2/coord/coordinator.go
- v2/coord/coordinator_test.go
- v2/dht.go
- v2/dht_test.go
- v2/internal/kadtest/context.go
- v2/notifee_test.go
- v2/query_test.go
Replaces the routing notification channel with a type that is passed in by the consumer. This allows tests waiting for routing notifications to deterministically buffer and inspect the entire set of notifications.
Tests in DHT package are a little more awkward to write since they have to pass in a RoutingNotifier but we need to do a pass over the test helpers anyway and should clean all of it up with some helper functions.
> Fix test flakes that wait for routing events

- v2/dht_test.go
- v2/notifee_test.go
- v2/query_test.go
- v2/routing.go
- v2/routing_test.go
- v2/topology_test.go
> Clean up DHT test helpers 

- v2/backend.go
- v2/config_test.go
- v2/handlers_test.go
- v2/internal/coord/coordinator.go
- v2/internal/coord/query/query.go
- v2/routing.go
- v2/routing_test.go
> feat: findProvidersAsync

- v2/dht.go
- v2/internal/coord/coordinator.go
- v2/internal/coord/event.go
- v2/internal/coord/query.go
- v2/internal/coord/routing.go
- v2/routing.go
- v2/stream.go
- v2/tele/log.go
- v2/tele/tele.go
Makes the logging a little more consistent and adds debug logging for key routing events to help with testing during integration.
> Logging improvements

- v2/backend.go
- v2/backend_provider.go
- v2/backend_provider_test.go
- v2/backend_record.go
- v2/backend_record_test.go
- v2/backend_trace.go
- v2/config.go
- v2/config_test.go
- v2/dht.go
- v2/dht_test.go
- v2/handlers.go
- v2/handlers_test.go
- v2/internal/coord/brdcst/brdcst.go
- v2/internal/coord/brdcst/config.go
- v2/internal/coord/brdcst/config_test.go
- v2/internal/coord/brdcst/pool.go
- v2/internal/coord/brdcst/pool_test.go
- v2/internal/coord/brdcst/static.go
- v2/internal/coord/coordinator.go
- v2/internal/coord/query/query.go
- v2/router.go
- v2/routing.go
- v2/routing_test.go
- v2/tele/tele.go
- v2/topology_test.go
> Implement SearchValue/GetValue

- internal/net/message_manager.go
ISSUE: https://github.com/libp2p/go-libp2p-kad-dht/issues/958
There is no need to re-establish the connection for context canceled error, otherwise a lot of memory will be generated when calling GetValue in large numbers.
**Looking forward to someone reviewing the code.**
> add ctx canceled err check

- handlers.go
When receiving a kademlia `FIND_NODE` request for its own peer id, a go-libp2p-kad-dht node will respond with its own peer record only. According to libp2p kademlia [spec](https://github.com/libp2p/specs/blob/master/kad-dht/README.md), it should reply with the `k` closest nodes.
> The libp2p Kademlia DHT offers the following types of operations:
> * Peer routing
>     * Finding the closest nodes to a given key via FIND_NODE.
> 3. Upon a response:
>     1. If successful the response will contain the k closest nodes the peer knows to the key Key. Add them to the candidate list Pn, except for those that have already been queried.
Depending on https://github.com/libp2p/specs/pull/609, nodes shouldn't even include their own peer records in the response (already known to the requester). This …
> findnode(self) should return multiple peers

- dht.go
- dht_test.go
- ext_test.go
Currently, nodes will always perform a `lookupCheck` (`FIND_PEER` request where receiver should reply with at least 1 peer record) before a peer is added to the routing table, and when refreshing the routing table.
This check should be performed only if the routing table is well populated. Otherwise, it is tricky to bootstrap a new DHT network as the first peers start with an empty routing table, and are unable to provide peer to others when requested by the `lookupCheck`.
The check will be skipped if the routing table contains less than `bucketSize` peers, which means that no bucket can be full. It implies that unresponsive peers making it to the routing table because the check was skipped will get evicted once `bucketSize` peers are present in the routing table, and they won't prevent …
> Fix: don't perform lookupCheck if not enough peers in routing table

- crawler/crawler.go
- dht.go
- fullrt/dht.go
- go.mod
- internal/net/message_manager.go
- netsize/netsize.go
- pb/message.go
- pb/protocol_messenger.go
- providers/providers_manager.go
- rtrefresh/rt_refresh_manager.go
Trying to clean up unnecessary dependencies by upgrading the old version of go-log v1.0.5 here. go-log v1.0.5 brings in `github.com/opentracing/opentracing-go` and other dependencies, which won't be removed until [go-libp2p-kbucket](https://github.com/libp2p/go-libp2p-kbucket/pull/132) also upgrades to go-log v2.5.1.
Related: https://github.com/libp2p/go-libp2p-kbucket/pull/132
> Upgrade to go-log v2.5.1

- dht.go
- dht_filters.go
- fullrt/dht.go
- query.go
- query_test.go
- routing.go
This PR builds on #974 and fixes a bug whereby `FindPeer` won't return results for peers behind NAT which only have `p2p-circuit` multiaddrs.
This fixes the regression [starting from v0.34 of go-libp2p](https://github.com/libp2p/go-libp2p/releases/tag/v0.34.0):
> Peers connected to the host via relayed or any other limited connection now report their connectivity state as Limited.
> NOTE: This changes the behavior of the `Connected` Connectedness state. Previously it included all limited connections and now it doesn't. To keep existing behavior in your code you can replace checks connectedness == network.Connected with connectedness != network.NotConnected
> chore: fix connectedness

- query_test.go
Reverting changes on `TestRTEvictionOnFailedQuery` introduced in https://github.com/libp2p/go-libp2p-kad-dht/pull/980, fixed in https://github.com/libp2p/go-libp2p/pull/2916.
This change was removed in https://github.com/libp2p/go-libp2p-kad-dht/commit/4667e81182cce3d559d3d784a289309311129376 in https://github.com/libp2p/go-libp2p-kad-dht/pull/976, but the commit was [overwritten](https://github.com/libp2p/go-libp2p-kad-dht/compare/4667e81182cce3d559d3d784a289309311129376..5669815d0188dd9f71d08d69daff9740ea777077) (by accident?). 
The commit was initially [removed](https://github.com/libp2p/go-libp2p-kad-dht/pull/974#issuecomment-2298578461) in https://github.com/libp2p/go-libp2p-kad-dht/pull/974 but not in https://github.com/libp2p/go-libp2p-kad-dht/pull/976.
No need to make a new …
> fix(query): reverting changes on TestRTEvictionOnFailedQuery

- go.mod
- records_test.go
`NewSeededRand` migrated from [boxo](https://github.com/ipfs/boxo) to [go-test](https://github.com/ipfs/go-test)
> fix: replace deprecated Boxo function

- dht.go
- dht_options.go
- internal/config/config.go
The current implementation uses [the internal MessagerImplementation](https://github.com/libp2p/go-libp2p-kad-dht/blob/master/internal/net/message_manager.go) always as a unique implementation. 
I've been trying to perform multiple operations/lookups in parallel using the same `dhtHost`, and the current logic of using a single simultaneous stream and request per peer is becoming a bottleneck to resolving each concurrent operation. 
(Check as reference #805 )  
This PR proposes a new DHT Option that allows users or projects to provide any custom `MessageSender`.
> Add new DHT option to provide custom pb.MessageSender

- crawler/crawler.go
Hey,
I'm running an IPFS node with the Accelerated DHT Client, but I'm seeing issues with the reprovider system showing `reprovider system not ready`. I've been debugging the fullrt code a little bit and it seems it's because the initial crawl never completes, because [this loop](https://github.com/libp2p/go-libp2p-kad-dht/blob/8170ac4e51f65e951d4544a32661457de06e2c6a/crawler/crawler.go#L183) never exits. Specifically, it seems that some of the worker goroutines get stuck trying to query some quic peers. See the below goroutine stacks to follow along.
```
goroutine 579 [select, 10 minutes]:
github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).NewStream(0x14001660480, {0x10676c6d8, 0x1400dbe6ff0}, {0x1401648def0, 0x26}, {0x1400200a8a0, 0x1, 0x1}) …
```
> Use timeout context for NewStream call

- crawler/crawler.go
This PR aims to correctly apply the fix from: 
- https://github.com/libp2p/go-libp2p-kad-dht/pull/996 (cc @MarcoPolo @guillaumemichel @ligustah)
It did not work as expected because `context.WithTimeout`  was created once per goroutine but was used for multiple queries within the `for p := range jobs` loop.
This meant once the timeout expires for the first query, all subsequent queries in that worker would immediately fail since they're using the same expired context. The crawl ended in ~15s instead of few minutes.
Fix is to have new context per job.
> fix(crawler): separate timeout per query

- routing.go
The following should help us to inspect more closely when additional peer routing requests are necessary when looking for providers. 
The context for this is someguy, whereby we observe that many providers are returned with no multiaddrs.
> feat: add more attributes to traces

- dht.go
- dht_net.go
- dht_options.go
- internal/config/config.go
This pull request adds a callback hook into the stream handler and will be called on every request.
> feat: add request callback config option

- dht_test.go
- dual/dual_test.go
- fullrt/dht.go
- handlers.go
- internal/util.go
- providers/providers_manager_test.go
- records_test.go
- routing.go
Copied `Hash` and `RFC3339` time functions over to `internal/` to stop depending on `boxo/util`.
See https://github.com/libp2p/go-libp2p-kad-dht/issues/846
> chore: remove boxo/util deps

- lookup.go
- query.go
- routing.go
Supersedes https://github.com/libp2p/go-libp2p-kad-dht/pull/799
* cleanup query code
* fixing query context cancelling reported in https://github.com/libp2p/go-libp2p-kad-dht/pull/799
> fix: query cleanup

- dht_test.go
Fixes https://github.com/libp2p/go-libp2p-kad-dht/issues/724
Test doesn't appear to be flaky anymore, I wasn't able to reproduce locally. Let's not skip it
> fix: don't skip TestContextShutDown

- rtrefresh/rt_refresh_manager_test.go
Fixes https://github.com/libp2p/go-libp2p-kad-dht/issues/722
`GenRandPeerID` doesn't actually generate a random peer ID, but it select one matching the CPL from the [preimage list](https://github.com/libp2p/go-libp2p-kbucket/blob/master/bucket_prefixmap.go).
The test was failing when the same peer was "randomly generated" twice and added to the routing table.
> fix: flaky TestSkipRefreshOnGapCpls

- providers/providers_manager_test.go
Fixes https://github.com/libp2p/go-libp2p-kad-dht/issues/725
I couldn't reproduce the failure locally. Let's not skip the `TestProvidesExpire`
> fix: don't skip TestProvidesExpire

- dht_test.go
- records_test.go
Removing skipped and deprecated `TestPubkeyExtract`, and well as some `t.Skip()` commented out.
> fix(tests): cleanup of skipped tests

- dht_test.go
Fixes https://github.com/libp2p/go-libp2p-kad-dht/issues/726
Test seems to fail because timeout value was too low.
> fix: increase timeout in TestProvidesMany

- dht_test.go
Fixes https://github.com/libp2p/go-libp2p-kad-dht/issues/1026
Test is flaky because of timing issues. The provider record is probably not added in the provider store by the time the FindProviders request hits `a`.
If prov isn't found at first try again. Retrying seems better than sleeping more.
> fix: flaky TestClientModeConnect

- dht_test.go
Fixes https://github.com/libp2p/go-libp2p-kad-dht/issues/1023
3 distinct failures reproduced locally
* `Application error 0x0 (local)` comes from `quic-go` and was occurring because `ctx` was cancelled already but we are trying to read from the stream. Returning after ctx cancel does the trick
* `Expected to get a provider back` solved like https://github.com/libp2p/go-libp2p-kad-dht/pull/1028
* `Well behaving DHT server should have been added to the server routing table` occurred just once locally. Give a second chance for `s1` to be included in `s0`'s routing table after sleeping if not found immediately.
> fix: Flaky TestInvalidServer

- dht_test.go
Fixes https://github.com/libp2p/go-libp2p-kad-dht/issues/1033
* Unable to reproduce failure locally
* Increased deadline from `5ms` to `30ms`
> fix: flaky TestFindPeerWithQueryFilter

- dht_test.go
Fixes https://github.com/libp2p/go-libp2p-kad-dht/issues/791
* to make sure that all peers are found, set `Resiliency` to `bucketSize`
* if self (`guy`) is among the closest peers of the key that is looked up, the test may fail
* in this case we don't look for the `bucketSize` closest peers, but for the `bucketSize+1` closest peers, excluding self, hence the last peer may not be correct
* fix: if self is among the closest peers, add it to the list of returned peers when checking for the closest peers
> fix: flaky TestFindPeerQueryMinimal

- dht_test.go
- dual/dual_test.go
Fixes https://github.com/libp2p/go-libp2p-kad-dht/issues/723
> fix: flaky TestSearchValue (dual)

- dht_test.go
Fixes https://github.com/libp2p/go-libp2p-kad-dht/issues/973
Adding test coverage for `/dns`, `/dns4`, `/dns6` and `/dnsaddr` addresses in TestAddrFilter.
> test: cover dns addresses in TestAddrFilter

- dual/dual_test.go
Fixes https://github.com/libp2p/go-libp2p-kad-dht/issues/1039
* unable to reproduce failure locally
* added verbose
> fix: flaky TestFindProviderAsync (dual)

- fullrt/dht.go
I don't think there was any guarantee that the you'd get back the same pointer for this interface check to work. And this won't work in go-multiaddr v0.15. 
By changing this and possibly backporting this fix users can use go-multiaddr v0.15 without having to also deal with breaking changes in kad-dht and boxo.
> fix addrsSoFar comparison

- crawler/crawler.go
- crawler/options.go
- fullrt/dht.go
Extending the TTL in the host's peerstore right after connecting is a no-op, since it is effective only [if the provided TTL is higher than the current one](https://github.com/libp2p/go-libp2p/blob/5e6f217d847e7c1c3f98197a54c9503d0303a7bb/p2p/host/peerstore/pstoremem/addr_book.go#L374-L377), and a remote peer that is `Connected` has a a [much higher](https://github.com/libp2p/go-libp2p/blob/5e6f217d847e7c1c3f98197a54c9503d0303a7bb/core/peerstore/peerstore.go#L48) TTL.
Hence we can fully remove the `dialAddressExtendDur`.
See https://github.com/libp2p/go-libp2p-kad-dht/issues/1061#issuecomment-2704316209 and https://github.com/libp2p/go-libp2p-kad-dht/pull/1053
Note that this is a breaking change.
> fix(crawler): remove peerstore no-op

- fullrt/dht.go
> cleanup: fullrt

- handlers.go
Until now, when a client sends an `ADD_PROVIDE` with no valid provider (either not matching the client's peer id, or missing addresses), the DHT Server will behave as if the operation was successful.
This change makes the DHT Server error when no valid providers are provided, which will close the stream (same behavior as other errors).
> fix: error on no valid provs

- providers/providers_manager_test.go
Attempt at fixing flaky `TestProvidesExpire`
Fixes https://github.com/libp2p/go-libp2p-kad-dht/issues/725
> tests: fix flaky TestProvidesExpire

- internal/metrics/metrics.go
The message type attribute was being overwritten with "UNKNOWN" because `attrOpt` was given after `attrSetOpt` (which contained the message type from the context) in the varargs.
I removed the message type "UNKOWN" from `RecordRequestSendOK` since its only called once and the context that is passed in has the message type attribute set.
The images bellow show the problem with an example query in victoria metrics.
> fix: use correct message type attribute in metrics

- lookup.go
- lookup_optim.go
The network size estimator is emitting a warning if it doesn't get exactly `bucketSize` peers in the `Track()` method.
If the network doesn't contain `bucketSize` peers altogether, the warning will constantly be emitted, which is undesirable and corrected in this PR.
See [this post](https://discuss.ipfs.tech/t/understanding-reprovider-behavior-with-go-ds-crdt/19279).
> fix: netsize warning

- fullrt/dht.go
Previously mutex wasn't released if `!ok`.
> fix: fullrt kMapLk unlock

- dht_test.go
Completes `TestFindClosestPeers` to ensure that the peers returned by `GetClosestPeers` are ordered in ascending distance to the target key.
> tests: GCP result ordering

- amino/defaults.go
- go.mod
- go.sum
- provider/datastore/keystore.go
- provider/datastore/keystore_test.go
The KeyStore is a datastore backed state to keep track of the keys (multihashes) that should be periodically reprovided to the DHT swarm.
The keys are stored by DHT keyspace locality. They are grouped by (constant size) prefix and indexed by this prefix in the datastore. Note that the key by which they are addressed is their Kademlia identifier, and not the hash from the multihash.
Readers (`Get()`) only make prefix requests, since the caller wants to retrieve all keys matching a specific set of peers in the network matching the keyspace prefix.
Writers (`Put()`) are expected to write random keys (not necessarily close in the keyspace).
Keys can be removed using `Delete()`.
Since it is tricky for kubo to determine whether a key …
> provider: keystore

- provider/provider.go
Scaffold for the `SweepingProvider` type and `Provider` interface as discussed in https://github.com/libp2p/go-libp2p-kad-dht/pull/1093.
> provider: SweepingProvider interface

- go.mod
- go.sum
- provider/internal/queue/prefix.go
- provider/internal/queue/provide.go
- provider/internal/queue/provide_test.go
- provider/internal/queue/reprovide.go
- provider/internal/queue/reprovide_test.go
---
This PR adds 2 queues implementations:
This queue keeps track of the prefixes associated with the keyspace regions that should be reprovided as soon as possible. These regions end up in the queue if the provider failed to reprovide them on time.
This queue keeps track of all the keys that should be provided as soon as possible. The keys are grouped by common prefix to optimize batch providing.
Both queues make use of the `prefixQueue`.
> provider: adding provide and reprovide queue

- provider/provider.go
Depends on https://github.com/libp2p/go-libp2p-kad-dht/pull/1098
---
Interface for polling the provide status of a specific key. Since this method isn't required for the provider to operate, this method isn't included in the `DHTProvider` interface https://github.com/libp2p/go-libp2p-kad-dht/pull/1093.
---
Merging this PR isn't urgent, since the method isn't implemented yet in https://github.com/libp2p/go-libp2p-kad-dht/pull/1082, and it isn't required for the providing to work.
> provider: ProvideStatus interface

- crawler/crawler.go
- crawler/options.go
Make the crawler's protocol messenger configurable.
I need this to track the number of messages that are sent out by the crawler when comparing the performance of the old and new provide systems.
> feat(crawler): configurable protocol messenger

- provider/datastore/keystore.go
- provider/datastore/keystore_test.go
- provider/internal/keyspace/key.go
- provider/internal/keyspace/key_test.go
- provider/internal/keyspace/trie.go
- provider/internal/keyspace/trie_test.go
- provider/provider.go
- provider/provider_test.go
---
`SweepingProvider.AddToSchedule` makes sure that prefixes covering the supplied keys are included in the schedule, so that the keys are reprovided in time.
This is necessary for when keys are added directly in the keystore, since adding a key to the keystore doesn't translate to scheduling its associated prefix for reprovide.
This will be used in the `dual.DHT` provider and composable DHT routers.
`SweepingProvider.RefreshSchedule` syncs the schedule with the keystore.
If keys have been added to the keystore, they will be reprovided as long as their associated prefix is scheduled. Since kubo handles garbage collection of keys that shouldn't be reprovided anymore by directly resetting the keystore, it is possible that new …
> provider: refresh schedule

- provider/internal/keyspace/trie.go
- provider/internal/keyspace/trie_test.go
- provider/provider.go
- provider/provider_test.go
Refactor of `closestPeerToPrefix` to use a trie to ensure keyspace coverage (instead of binary prefix stack).
> refactor(provider): closestPeerToPrefix coverage trie

- provider/provider.go
As discussed, we don't want to track timestamp for every provided multihash, since it adds a lot of overhead. Moreover, the feature would only benefit a small number of users, but all users need to pay the price of logging timestamps.
* Removed the `ProvideStatus` command (scaffold)
* Logged multihashes that were just provided to `DEBUG` so that users are able to know which multihashes were provided (with timestamp) if necessary.
cc: @gammazero @lidel
> refactor: remove provider status command

- provider/internal/keyspace/trie.go
We were loading large slices in memory in the recursive `allocateToKClosestAtDepth` even when not needed (`matchingItems := AllValues(matchingItemsBranch, bit256.ZeroKey())`.
Optimizing memory usage.
> fix(provider): memory usage
