dht_test.go
handlers.go
records.go

From ipfs/go-ipfs#8f362d2b1500809cbae2ee08c2b42a6f226a10b8

dht: protect against a panic in case record on pbmessage is nil

---

LICENSE
README.md

Usage section still needs to be filled out.

Standardize README and add MIT License

---

dht_bootstrap.go

BootstrapWithConfig leaks a ticker as described in #43.
This patch fixes the issue by implementing the ticker as a periodic process (instead of driving with a channel).
Closes #43

fix ticker leak in BootstrapWithConfig

---

routing.go

Thanks @mildred for catching this and providing a patch.
closes #51

Add addresses from received provider records

---

records.go

See https://github.com/ipfs/go-ipfs/issues/3896. Depends on https://github.com/libp2p/go-libp2p-peer/pull/13.

Try extracting public key from peer identity

---

.gx/lastpubver
dht.go
notif.go
notify_test.go

Properly track connections to peers in the DHT.

---

.gx/lastpubver
package.json

gx: remove bbloom dep

---

.travis.yml
providers/providers_test.go

fix: go1.9 monotonic time (for real this time)

---

dht_net.go
ext_test.go
package.json

* Fixup for reset/close differences.
* Retry on failed stream reads, not only failed stream writes, because writes will succeed on half-closed streams.

update stream muxer

---

dht.go
handlers.go
lookup.go
providers/providers.go
routing.go

Try to preallocate slices up-front instead of repeatedly reallocating.

optimize allocations

---

dht_test.go
lookup.go
lookup_test.go

handle paths as DHT keys

---

dht_test.go

These aren't errors, don't log them as such.

nit: be less noisy when testing

---

records.go
records_test.go

See https://github.com/libp2p/go-libp2p-kad-dht/issues/88#issuecomment-364824874

Only retrieve one value when fetching public key from DHT

---

dht.go

issue outline: https://github.com/ipfs/go-log/issues/23
License: MIT
Signed-off-by: ForrestWeston <forrest@protocol.ai>

fix loggable collision on peer and target

---

.gx/lastpubver
package.json
routing.go

Fix panic in FindPeersConnectedToPeer

---

.gx/lastpubver
lookup.go
package.json

not really an error, it doesn't stop us from logging, and it just spams for things that do random queries.

downgrade Error log for loggable formatting

---

dht.go

remove redundant error check

---

dht_net.go

When a peer sends use a EOF after they're done sending us messages, we should be
polite and send one back.

be more polite about closing streams

---

dht.go
dht_net.go
dht_test.go
handlers.go
routing.go

fix dht client bugs

---

.gx/lastpubver
dht_bootstrap.go
package.json

Closes #178 and bumps the gx version

Fix docstring and gx bump

---

README.md

fix(readme): fix typo error

---

dht.go

Hi, I add the ```RoutingTable``` function to return dht's routingTable, so that user can use the 
routingTable to extend there protocol. @Stebalien

add RoutingTable func

---

dht.go
dht_bootstrap.go
dht_test.go
routing.go

Includes deferral of error package change. Might be worth squashing this when merging (or not, I think I managed to do it correctly with git, according to https://stackoverflow.com/a/1078209/149482).

Tidy up bootstrapping

---

dial_queue.go

Was leading to a todocounter panic.

Fix a race in dial queue

---

handlers.go
log_test.go

Some changes to logging after extensive debugging sessions.

Alter some logging

---

dht_test.go
dial_queue.go
query.go

fixes #276
Also fixes handling of closed in queue.

fix(dialQueue): account for failed dials

---

dial_queue.go
dial_queue_test.go
query.go

Fixes #292 (see discussion there).

defer dialqueue action until initial peers have been added

---

dht.go
dht_test.go
dial_queue.go
handlers.go
providers/providers.go
query.go
util.go

Ran a linter inspired by some wins elsewhere.

golangci-lint run -D errcheck

---

dht.go
subscriber_notifee.go

Fix issues with startup:
1. Don't start subprocesses till fully initialized.
2. Use goprocess correctly.

fix initialization issues

---

dht.go
dht_test.go
handlers.go

The first byte of the key is used to select the striped lock.

Striped locks for atomic Dht updates

---

routing.go

fix deadline calculation in Provide function of routing.go

---

dht.go
handlers.go
lookup.go
opts/options.go
routing.go

This transplants #361 to master, and adds godoc.
(Need it for testground experimentation).

Make routing table bucket size configurable

---

dht.go

Remove incorrect doc

---

pb/message.go

@Stebalien 
We already adjust it during decoding.

Adjust cluster level while encoding as well

---

dht.go
dht_test.go
subscriber_notifee.go

@aschmahmann 
For https://github.com/libp2p/go-libp2p/issues/778

Simple Refactor & tests for Protocol changes & mode switches

---

providers/providers.go

These errors all mean something is going very wrong.

fix(providers): upgrade warnings to errors

---

metrics/metrics.go

give views names again

---

handlers_test.go

add benchmark for handleFindPeer

---

dht.go
dht_test.go

@Stebalien 
For https://github.com/libp2p/go-libp2p-kad-dht/issues/476.

Close context correctly

---

dht.go
dht_test.go
notify_test.go
query.go
routing.go
routing_options.go

@aarshkshah1992 @Stebalien these should be pretty straightforward. Just wanted another set of eyes (especially on the FindProvidersAsync count = 0) to make sure I haven't missed anything obvious.

Quorum fixes and misc cypress fixes

---

qpeerset/qpeerset_test.go

Qpeerset Tests for https://github.com/libp2p/go-libp2p-kad-dht/pull/498

Tests for Async Query Logic

---

dht.go
dht_options.go
dht_test.go
lookup.go
query.go
routing.go

Remove disjoint queries

---

events.go
go.mod
qpeerset/qpeerset.go
qpeerset/qpeerset_test.go
query.go

Please review carefully the changes in termination condition checks.

Emit events during async query.

---

dht_bootstrap.go

fixes: https://github.com/ipfs/go-ipfs/issues/7206

fix: avoid blocking when bootstrapping

---

dht_net.go

minor. noticed while looking at why a lock had contention.

clean up a channel that was dangling

---

dht_bootstrap_test.go

Put back TestSelfWalkOnAddressChange

---

dht.go
dht_bootstrap_test.go
dht_options.go
go.mod
go.sum
rtrefresh/rt_refresh_manager.go
rtrefresh/rt_refresh_manager_test.go

Reduce churn in lower buckets

---

dht.go
dht_options.go
dht_test.go

To be merged into master after #690 is merged.

feat: add advanced V1ProtocolOverride option to be used by legacy networks

---

fullrt/dht.go
fullrt/options.go

Implement the ability to configure provider manager options in `fullrt` DHT client implementation.

Make provider manager options configurable in `fullrt`

---

v2/internal/coord/brdcst/followup.go
v2/internal/coord/brdcst/pool_test.go
v2/internal/coord/coordinator.go
v2/routing_test.go

Improves test coverage for routing.Routing Provide()
relates to #913

add provide routing tests

---

go.mod
go.sum

I did a kad-dht update to apply the recent kbucket update and others.

chore: update version

---

dht_options.go
pb/message.go

fix some function names in comment

chore: fix some function names in comment

---

dual/dual_test.go

fixes https://github.com/libp2p/go-libp2p-kad-dht/issues/1055

tests: flaky TestSearchValue (dual)

---

provider/dual/options.go
provider/dual/provider.go
provider/keystore/keystore.go
provider/keystore/keystore_test.go
provider/keystore/options.go
provider/keystore/resettable_keystore.go
provider/keystore/resettable_keystore_test.go
provider/options.go
provider/provider.go
provider/provider_test.go

Part of #1095 
* Move `provider/datastore` to `provider/keystore`
* rename `KeyStore` to `Keystore`

keystore: rename

---

go.mod
go.sum
provider/buffered/provider.go
provider/dual/provider.go

Addressing @gammazero 's [review](https://github.com/libp2p/go-libp2p-kad-dht/pull/1095#pullrequestreview-3231636254) in #1095.

provider: more minor fixes
